big_models:
    num_samples_in: 500
    num_samples_out: 500

small_models:
  num_samples_in: 1200
  num_samples_out: 1200

random_forest:
  big_model:
    num_of_estimators: 20
    num_of_jobs: 10
  small_model:
    num_of_estimators: 4
    num_of_jobs: 2
  models_location: 'random_forest'

polynomial:
  big_model:
    degree: 5
  small_model:
    degree: 3
  models_location: 'polynomial'

neural_network:
  batch_size: 32
  epochs: 150
  models_location: 'neural_network'

models_location: 'models'
